config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  mount RailsAdmin::Engine => '/dashboard', as: :rails_admin

  get 'tags/:tags', to: 'books#index', as: :tags
  get 'tags/', to: 'books#index'

  resources :categories, only: [:index, :show], path: '' do
    resources :books, param: :slug, except: [:index, :update, :destroy, :edit], path: '' do
      resources :comments, except: :index
    end
  end

  resources :books, only: [:new, :create]

  root 'categories#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', as: :signout
  get '/locale/change/:locale', to: 'sessions#change_locale', as: :change_locale
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/book.rb
class Book < ActiveRecord::Base
  include BooksHelper
  include PgSearch

  acts_as_taggable

  belongs_to :category
  has_many :comments
  has_many :book_translations
  before_create :generate_slug
  validates :title, presence: true, uniqueness: { case_sensitive: false }

  scope :published, ->{ where(published: true).order(created_at: :desc) }

  translates :title, :author, :publisher, :description, :fallbacks_for_empty_translations => true
  pg_search_scope :search_everywhere, associated_against: {book_translations: [:title, :author, :description]}

  def generate_slug
    title = self.title.mb_chars.downcase
    self.slug = cyr_to_lat(title).gsub(/[^a-zA-Z0-9]+/, '-').gsub(/-{2,}/, '-').gsub(/^-|-$/, '')
  end
end

app/models/book_translation.rb
class BookTranslation < ActiveRecord::Base
  belongs_to :book
end

app/models/category.rb
class Category < ActiveRecord::Base
  include FriendlyId
  friendly_id :title
  has_many :books
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :book, dependent: :destroy
  belongs_to :user, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
  helper_method :current_user

  def set_locale
    if cookies[:site_locale] && I18n.available_locales.include?(cookies[:site_locale].to_sym)
      l = cookies[:site_locale].to_sym
    else
      l = I18n.default_locale
      cookies.permanent[:site_locale] = l
    end
    I18n.locale = l
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def not_found
    raise ActionController::RoutingError.new('Routing Error')
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:edit, :update, :destroy]
  before_action :redirect_unless_current_user, except: :show

  def index
    @tags = Book.tag_counts_on(:tags)

    if params[:tags]
      @chosen_tags = params[:tags].split('&')
      if @chosen_tags.size > 1
        @books = Book.tagged_with(@chosen_tags, match_all: true)
      else
        @books = Book.tagged_with(@chosen_tags)
      end
    else
      # view only tags if no one tag has been chosen
      # or reditect redirect_to root_path here?
    end
  end

  def show
    @book = Book.find_by_slug(params[:slug]) or not_found
    @book.views += 1
    @book.save

    @related_book = @book.find_related_tags
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      redirect_to root_path, notice: 'Book was successfully created.'
    else
      render :new
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_url, notice: 'Book was successfully destroyed.'
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :publisher, :year, :link, :description, :language, :slug, tag_list: [])
  end

  def redirect_unless_current_user
    if Rails.env.production?
      redirect_to root_path, notice: 'Пожалуйста, войдите через Twitter или Github'
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    #refactor
    if params[:search]
      @books = Book.search_everywhere(params[:search])
      if @books.size > 0
        @books
      else
        @books = Book.published
        flash.now[:notice] = "There wasn't found any book."
      end
    end
    @tags = Book.tag_counts_on(:tags)
  end

  def show
    @category = Category.friendly.find(params[:id])
    @books = @category.books
    @tags = @books.tag_counts_on(:tags)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action do
    # TODO: Refactor
    unless Rails.env.test?
      redirect_to root_path, notice: 'Пожалуйста, авторизуйтесь через социальные сети.' unless params[:authenticity_token]
    end
  end

  def create
    @book = Book.find_by_slug(params[:book_slug])
    @category = @book.category

    if @book.comments.include? Comment.where(user_id: current_user.id)
      redirect_to category_book_path(@category, @book.slug), notice: 'Вы уже оставили комментарий!'
    end
    @comment = @book.comments.build(comment_params)
    @comment.user_id = current_user.id
    @comment.language = I18n.locale
    if @comment.save
      redirect_to category_book_path(@category, @book.slug), notice: 'Спасибо за комментарий!'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:book_id, :user_id, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Signed out!"
  end

  def change_locale
    l = params[:locale].to_s.strip.to_sym
    l = I18n.default_locale unless I18n.available_locales.include?(l)
    cookies.permanent[:site_locale] = l
    redirect_to request.referer || root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end

  def remove_tag_from_url(tag)
    current_url = request.original_url
    current_url.gsub("&" << tag.name, '').gsub(tag.name, '').gsub('/&', '/') if current_url.include? tag.name
  end

  def add_tag_to_url(tag)
    current_url = request.original_url
    if current_url.include? "/tags"
      if params[:tags]
        current_url << "&" << tag.name
      else
        current_url << tag.name
      end
    else
      tags_path(tag.name)
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
  def cyr_to_lat(str)
    str.gsub('а', 'a').gsub('б', 'b').gsub('в', 'v').gsub('г', 'g').gsub('д', 'd').gsub('е', 'e').gsub('ё', 'e').gsub('ж', 'zh').gsub('з', 'z').gsub('и', 'i').gsub('й', 'i').gsub('к', 'k').gsub('л', 'l').gsub('м', 'm').gsub('н', 'n').gsub('о', 'o').gsub('п', 'p').gsub('р', 'r').gsub('с', 's').gsub('т', 't').gsub('у', 'u').gsub('ф', 'f').gsub('х', 'h').gsub('ц', 'c').gsub('ч', 'ch').gsub('ш', 'sh').gsub('щ', 'sh').gsub('ъ', '').gsub('ы', 'i').gsub('ь', '').gsub('э', 'e').gsub('ю', 'yu').gsub('я', 'ya')
  end

  def sort_comments_by(lang)
    comments_ru = []
    comments_en = []
    @book.comments.each do |comment|
      case comment.language
      when "ru"
        comments_ru << comment
      else
        comments_en << comment
      end
    end
    lang == "ru" ? comments_ru : comments_en
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book.html.slim
.col-sm-3
  .book
    .book__link= link_to category_book_path(book.category, book.slug) do
      .book__img= icon('book', class: 'fa-5x')
      h4.book__title= truncate book.title, length: 40
      .book__description
        .about.pull-left= truncate(book.author, length: 80)
        .about.pull-left= truncate(book.publisher, length: 80)
        .year.pull-right.text-right= book.year

app/views/books/_comments.html.slim
- if current_user && @book.comments.where(user_id: current_user.id).blank?
  h3 #{t('.add_comment')}:

  = form_for( [@book, @book.comments.build], url: category_book_comments_path(@book.category, @book.slug)) do |f|
    p= f.text_area :body
    p= f.submit value: t('.create'), class:'btn btn-primary'
- else
  h4.bg-danger.text-danger #{t('.warning')}

app/views/books/_comments_tab.html.slim
- unless current_user
  p
    strong.text-success.bg-success #{t('.to_comment')}

- sort_comments_by(lang).each do |comment|
    p
      strong= comment.user.try(:name)
      ' :
      = comment.body

app/views/books/_tag_cloud.html.slim
.container.with-tooltip data-toggle='tooltip' data-placement='top' title='#{t('tags.add_tooltip')}'
  .tags.text-center
    - tag_cloud(@tags, %w(menu_button)) do |tag, css_class|
      - if request.original_url.include? tag.name and request.original_url.include? "/tags"
        = link_to(tag.name, remove_tag_from_url(tag) , :class => "menu__button checked_menu__button")
      - else
        = link_to(tag.name, add_tag_to_url(tag) , :class => "menu__button")

app/views/books/index.html.slim
= render 'tag_cloud'

-if @books
  hr
  - @books.reorder(views: :desc).each do |book|
    = render 'books/book', book: book

app/views/books/new.html.slim
h3.text-center= t('.add_book')

.col-sm-8.col-sm-offset-2
  = simple_form_for [@category, @book] do |f|
    = f.input :title, label: t('.title')
    = f.input :author, label: t('.author')
    = f.input :year, label: t('.year')
    = f.input :link, label: t('.link')
    = f.input :description, label: t('.description')
    = f.input :language, label: t('.lang')

    .text-center= f.button :submit, t('.create')

app/views/books/show.html.slim
.book__show
  h3= @book.title
  .col-sm-8
    small= icon('eye', @book.views)
    p
      strong=> "#{t('.author')}:"
      = @book.author
    p
      strong=> "#{t('.publisher')}:"
      = "#{@book.publisher}, #{@book.year}"
    p
      strong=> "#{t('.buy')}:"
      = link_to truncate(@book.link, length: 50), @book.link
    p
      strong=> "#{t('.description')}:"
      = @book.description
    p
      strong=> "#{t('.lang')}:"
      = @book.language

  .col-sm-4.cover
    .text-center= icon('book', class: 'fa-5x')

  .col-sm-12
    h4= t('related_books')
    - @related_book.each do |book|
      = link_to book.title, category_book_path(book.category, book.slug)

  .col-sm-12
    div role="tabpanel"
      ul.nav.nav-tabs role="tablist"
        li.active role="presentation"
          a href="#russian" aria-controls="russian" role="tab" data-toggle="tab" #{t('.ru_comment')}
        li role="presentation"
          a href="#english" aria-controls="english" role="tab" data-toggle="tab" #{t('.en_comment')}

      .tab-content
        #russian.tab-pane.active role="tabpanel"
          = render partial: 'books/comments_tab', locals: {lang: "ru"}
          - if current_user
            = render 'books/comments'
        #english.tab-pane role="tabpanel"
          = render partial: 'books/comments_tab', locals: {lang: "en"}
          - if current_user
            = render 'books/comments'

app/views/categories/index.html.slim
- if params[:search].present?
  h3.text-center= t('.search-results')
  - @books.each do |book|
    = render 'books/book', book: book
- else
  - Category.find_each do |category|
    h3.text-center= category.title.capitalize
    .top-books
      - category.books.limit(4).reorder(views: :desc).each do |book|
        = render 'books/book', book: book

app/views/categories/show.html.slim
= render 'books/tag_cloud'

hr
.books
  = render @books

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title>Allthebooks</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name='viewport' content='width=device-width, initial-scale=1'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='description' content=''>
  <link rel='apple-touch-icon' href='apple-touch-icon.png'>
</head>
<body>
<%= render 'shared/top_header' %>

<div class='container'>
  <%= render partial: 'shared/flash_messages', flash: flash %>
  <%= yield %>
</div>

</body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= alert_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_search_bar.html.slim
.pull-right.search
  = form_tag root_path, method: 'get' do
    = text_field_tag :search, params[:search], placeholder: "#{t('search')}", class: 'search__input'
    = button_tag nil, name: nil, class: 'search__button' do

app/views/shared/_top_header.html.slim
nav#header
  .container
    header.header
      ul.header_menu
        - Category.find_each do |category|
          - if category.books.any?
            li.header_menu__item= link_to category.title.capitalize, category

      ul.header_menu.pull-right
        - if current_user
            li.header_menu__item= link_to t('.add_book'), new_book_path
            li.header_menu__item.disabled= link_to "#{t('.hi')}, #{current_user.name}", ''
            li.header_menu__item= link_to t('.logout'), '/signout'

        - else
            li.header_menu__item.disabled
              a.with-tooltip data-toggle='tooltip' data-placement='bottom' title='Авторизуйтесь через Twitter или Github'= t('.add_book')
            li.header_menu__item= link_to t('nav.login_github'), '/auth/github'
            li.header_menu__item= link_to t('nav.login_twitter'), '/auth/twitter'

        li.header_menu__item.dropdown
          a.dropdown-toggle data-toggle='dropdown' href="#" #{t('.lang')}
            <span class="caret"></span>
          ul.dropdown-menu role="menu"
            li= link_to t('.en'), change_locale_path(:en)
            li= link_to t('.ru'), change_locale_path(:ru)

      hr
      .container
        .header__bottom
          h1.logo= link_to 'All The Books', root_path
          = render 'shared/search_bar'